import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidenav from "./components/sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col h-screen md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <Sidenav />
          </div>

          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
